### PR TITLE
Add Travis CI build

### PR DESCRIPTION
**Pull request by jasp00**
This request adds continuous integration support with [Travis CI](https://travis-ci.org/). Maintainers should enable this service for this repository.

These Travis files also serve as documentation about how to properly build the application with free tools. Contribution guide does not seem clear enough, since versions from F-Droid do not ship gettext translations.

Build in Ubuntu bionic is disabled because the system is broken. Build in Debian stretch works. Resulting APK file is cleaner than the current one provided in Andor's Trail server.

### CODE REVIEW

**Comment by Chriz76** [comment]
Hello Javier,

Thank you for your contribution. 

Besides being a documentation Travis CI could also help with automated tests. I will talk with my collegues in the dev team, but currently I see no problem in adding it. We will have to check licenses, etc.

Could you please move the changes to the German file to it's own PR (if they are needed at all). Also the SDK is too low. That is also the reason why you couldn't use VERSION_CODES.P. Could the unused bionic gradle be removed?

Greetings 
Chris

**Comment by jasp00** [comment]
> Could you please move the changes to the German file to it's own PR (if they are needed at all).

They are present in #15, but they are still required for a successful build.

> Also the SDK is too low.

This SDK is the only free one available.

> That is also the reason why you couldn't use VERSION_CODES.P.

I have moved the source change to a build patch, thus sources in repository are clean.

> Could the unused bionic gradle be removed?

Done.

**Comment by Chriz76** [comment]
Sorry that it took me so Long to answer.

I would like to include your PR as a build reference in the AT sources. I will remove the changs to the PO file. 

If I understand you correctly it will not be able to build against newer SDKs. But this is required by Google to upload to the playstore. Wyh is it not possible? A patch every time code from newer SDKs is used is not an option.

For a full build there is even more to do. See https://andorstrail.com/viewtopic.php?f=11&t=6483

**Comment by jasp00** [comment]
> If I understand you correctly it will not be able to build against newer SDKs. But this is required by Google to upload to the playstore. Wyh is it not possible?

Using newer SDKs might be possible or not. I am just saying this patch is based on the only free-software SDK available for the system.

> See https://andorstrail.com/viewtopic.php?f=11&t=6483

I am not authorized to read that forum.

**Comment by Chriz76** [comment]
Merged it to NutAndor so it will be included in the official sources when we do the next release. Only as reference for building.

**Comment by Chriz76** [comment]
Merged it to NutAndor so it will be included in the official sources when we do the next release. Only as reference for building.

**Comment by Chriz76** [comment]
Hello Javier, thank you for your contributions. I don't think we already included you in the authors. Do you want to be added and using what name? Greetings Chris

**Comment by jasp00** [comment]
I am already in the Git log, so do as you see fit. If you include me in authors, please use my full name.

**Pull request closed without merging**
